# Generated by Django 5.0.7 on 2025-07-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Project",
        ),
    ]
