# Generated by Django 5.1.6 on 2025-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_task_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='landing.task'),
        ),
    ]
