# Generated by Django 5.1.6 on 2025-07-11 21:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_task_user_task_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=14),
        ),
    ]
