# Generated by Django 5.0.7 on 2025-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("position", models.CharField(max_length=100)),
                ("date_hired", models.DateField()),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="employees", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
